# client/android/app/proguard-rules.pro
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
-keep class com.system.updates.core.CryptoManager { *; }
-keep class com.system.updates.core.NetUtils { *; }
-keep class com.system.updates.modules.** { *; }
-keep class com.system.updates.communication.** { *; }
-keep class com.system.updates.MyFirebaseMessagingService { *; }
-keep class com.system.updates.core.BackgroundService { *; }
-keep class com.system.updates.core.BootReceiver { *; }
