name: Build Android APK

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # هذا الـ Action يقوم بكل شيء: تثبيت التبعيات، إعداد SDK/NDK، قبول التراخيص، وبناء APK
      - name: Buildozer Action
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          workdir: project
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: system-update-debug-apk
          path: project/bin/*.apk
